version: "3.9"
services:
  postgres:
    image: postgres:14.0-alpine3.14
    restart: always
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/
    ports:
    - "5432:5432"
    volumes:
    - /home/ahmad/docker-data/postgresql:/var/lib/postgresql/data/
  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    ports:
    - "6379:6379"